In [1]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,$53.00,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,$64.00,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,$73.00,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,$90.00,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,$49.00,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   object
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 548.6+ KB
None

In [4]:
print(df.describe(include="all"))

        Customer ID          Age Gender Item Purchased  Category  \
count   3900.000000  3900.000000   3900           3900      3900
unique          NaN          NaN      2             25         4
top             NaN          NaN   Male         Blouse  Clothing
freq            NaN          NaN   2652            171      1737
mean    1950.500000    44.068462    NaN            NaN       NaN
std     1125.977353    15.207589    NaN            NaN       NaN
min        1.000000    18.000000    NaN            NaN       NaN
25%      975.750000    31.000000    NaN            NaN       NaN
50%     1950.500000    44.000000    NaN            NaN       NaN
75%     2925.250000    57.000000    NaN            NaN       NaN
max     3900.000000    70.000000    NaN            NaN       NaN

       Purchase Amount (USD) Location  Size  Color  Season  Review Rating  \
count                   3900     3900  3900   3900    3900    3863.000000
unique                    81       50     4     25       4            NaN
top                  $94.00   Montana     M  Olive  Spring            NaN
freq                      62       96  1755    177     999            NaN
mean                     NaN      NaN   NaN    NaN     NaN       3.750065
std                      NaN      NaN   NaN    NaN     NaN       0.716983
min                      NaN      NaN   NaN    NaN     NaN       2.500000
25%                      NaN      NaN   NaN    NaN     NaN       3.100000
50%                      NaN      NaN   NaN    NaN     NaN       3.800000
75%                      NaN      NaN   NaN    NaN     NaN       4.400000
max                      NaN      NaN   NaN    NaN     NaN       5.000000

       Subscription Status  Shipping Type Discount Applied Promo Code Used  \
count                 3900           3900             3900            3900
unique                   2              6                2               2
top                     No  Free Shipping               No              No
freq                  2847            675             2223            2223
mean                   NaN            NaN              NaN             NaN
std                    NaN            NaN              NaN             NaN
min                    NaN            NaN              NaN             NaN
25%                    NaN            NaN              NaN             NaN
50%                    NaN            NaN              NaN             NaN
75%                    NaN            NaN              NaN             NaN
max                    NaN            NaN              NaN             NaN

        Previous Purchases Payment Method Frequency of Purchases
count          3900.000000           3900                   3900
unique                 NaN              6                      7
top                    NaN         PayPal         Every 3 Months
freq                   NaN            677                    584
mean             25.351538            NaN                    NaN
std              14.447125            NaN                    NaN
min               1.000000            NaN                    NaN
25%              13.000000            NaN                    NaN
50%              25.000000            NaN                    NaN
75%              38.000000            NaN                    NaN
max              50.000000            NaN                    NaN

In [5]:
print(df.isnull().sum())

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x:x.fillna(x.median()))

In [7]:
print(df.isnull().sum())

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
#convert all column in lower case and remove space with under_score
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(" ","_")
df=df.rename(columns={"purchase_amount_(usd)" : "purchase_amount"})

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [10]:
#create a column age_group
labels=["Young Adult","Adult","Middle-Aged","Senior"]
df["age_group"]=pd.qcut(df["age"],q=4,labels=labels)

In [11]:
df[["age","age_group"]].head(10)

   age    age_group
0   55  Middle-Aged
1   19  Young Adult
2   50  Middle-Aged
3   21  Young Adult
4   45  Middle-Aged
5   46  Middle-Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-Aged

In [12]:
#create column purchase_frequency_Days
frequency_mapping={"Fortnightly":14,
                   "Weekly":7,
                   "Monthly":30,
                   "Quarterly":90,
                   "Bi-Weekly":14,
                   "Annually":365,
                   "Every 3 Months":90
                  }
df["purchase_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)

In [13]:
df[["purchase_frequency_days","frequency_of_purchases"]].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [14]:
df[["discount_applied","promo_code_used"]].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [15]:
(df["discount_applied"]==df["promo_code_used"]).all()

np.True_

In [16]:
df=df.drop("promo_code_used",axis=1)

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [18]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\user\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\user\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
from sqlalchemy import create_engine
username = "postgres"
password = "satyam123"
host = "localhost"
port= "5432"
database = "customer_behavior"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data Successfully loaded into table '{table_name}' in database '{database}'.")

Data Successfully loaded into table 'customer' in database 'customer_behavior'.

In [20]:
from sqlalchemy import create_engine
username = "postgres"
password = "satyam123"
host = "localhost"
port= "5432"
database = "customer_behavior"
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

try:
    conn= engine.connect()
    print("connected successfully!")
    conn.close()
except Exception as e:
    print(e)

connected successfully!